name: sorting_hat
description: "A test task Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  riverpod: 2.6.1
  flutter_riverpod: 2.6.1
  riverpod_annotation: 2.6.1
  http: 1.3.0
  advanced_search: 2.2.4
  flutter_svg: 2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 3.0.1
  riverpod_lint: 2.3.10

flutter:

  uses-material-design: true

  assets:
    - assets/icons/

